**NSW Traffic Volume Viewer Analytics**

***Download Traffic Volume Viewer Data***

This notebook has been developed to download traffic volume data from the TfNSW Traffic Volume Viewer website - see: https://roads-waterways.transport.nsw.gov.au/about/corporate-publications/statistics/traffic-volumes/aadt-map/index.html#/?z=6

In [1]:
# Import dependency packages
import os
import pandas as pd
import glob
import zipfile
import datetime
import urllib.request
from pathlib import Path

time_start = datetime.datetime.now()
print(time_start)

2021-08-15 15:05:26.366534

In [2]:
# Specify the directory on your machine where the CSV files are to be saved.
base_dir = os.getcwd() 
data_dir = base_dir
inputs_dir = os.path.join(data_dir, 'Inputs')
traffic_data_dir = os.path.join(inputs_dir,'Traffic_Data')
outputs_dir = os.path.join(data_dir, 'Outputs') # Note: not used in this notebook
print(base_dir)

C:\Users\peter\Documents\GitHub\NSW_Traffic_Volume_Viewer_Analytics_dev

***Download Data***

The following cells download data from the NSW Traffic Volume Viewer website in CSV format.

In [4]:
# Download Station Information
web_url = "https://rms-uat.cartodb.com/api/v2/sql?format=CSV&filename=Traffic_Volume_Viewer_Station_Information&q=SELECT%20station_id,%20full_name,%20name,%20road_name,%20common_road_name,%20secondary_name,%20suburb,%20post_code,%20lga,%20rms_region,%20distance_to_intersection,%20intersection,%20road_number,%20link_number,%20mab_identifier,%20device_type,%20permanent_station,%20vehicle_classifier,%20road_on_type,%20road_classification_type,%20road_classification_admin,%20wgs84_latitude,%20wgs84_longitude,%20ST_SetSRID(ST_MakePoint(CAST(wgs84_longitude%20AS%20FLOAT),%20CAST(wgs84_latitude%20AS%20FLOAT)),4326)%20AS%20the_geom%20FROM%20ds_aadt_reference%20WHERE%20publish=%271%27%20ORDER%20BY%20station_id"
download_fp = os.path.join(traffic_data_dir, 'station_information.csv')
try: 
    urllib.request.urlretrieve(web_url, download_fp)
except:
    print("No file available.")

# Read and view data
station_information_df = pd.read_csv(download_fp)
station_information_df.head()

,the_geom,station_id,full_name,name,road_name,common_road_name,secondary_name,suburb,post_code,lga,...,link_number,mab_identifier,device_type,permanent_station,vehicle_classifier,road_on_type,road_classification_type,road_classification_admin,wgs84_latitude,wgs84_longitude
0,0101000020E61000004B1FBAA0BEE66240FD32182312ED...,01001,"Sydney Harbour Bridge, North of Hickson Road",Sydney Harbour Bridge,Bradfield Highway,Bradfield Highway,North of Hickson Road,Milsons Point,2061.0,Sydney,...,20,NaN,Trafficorder Dual Tube Classifier,0,1,OnBridge,Highway,State,-33.852116,151.210770
1,0101000020E6100000BB253960D7E66240179CC1DF2FEE...,01003,"Sydney Harbour Tunnel, North of Cahill Expressway",Sydney Harbour Tunnel,Sydney Harbour Tunnel,"Sydney Harbour Tunnel.sydney Harbour Tunnel, S...",North of Cahill Expressway,Sydney,2000.0,Sydney,...,10,M1,Trafficorder Loop Counter,1,0,InTunnel,NaN,State,-33.860836,151.213791
2,0101000020E61000007730629F80E6624082397AFCDEEE...,01004,"Western Distributor, West of Sussex Street",Western Distributor,Western Distributor,"Western.western Distributor, Sydney",West of Sussex Street,Sydney,2000.0,Sydney,...,18,NaN,Trafficorder Loop Counter,1,0,OnBridge,Distributor,State,-33.866180,151.203201
3,0101000020E6100000EA5DBC1FB7E66240982F2FC03EEE...,01011,"Cahill Expressway, East of Pitt Street",Cahill Expressway,Cahill Expressway,"Cahill.cahill Expressway, Sydney",East of Pitt Street,Sydney,2000.0,Sydney,...,180,NaN,Trafficorder Loop Counter,1,0,OnBridge,Expressway,State,-33.861290,151.209854
4,0101000020E61000000F7EE2007AE66240AE62F19BC2F0...,01323,"Ultimo Road, East of Darling Drive",Ultimo Road,Ultimo Road,Ultimo Road,East of Darling Drive,Haymarket,2000.0,Sydney,...,-10,NaN,Trafficorder Tube Axlepair Counter,0,0,OnGround,Road,Local,-33.880939,151.202393

In [5]:
# ds_aadt_reference
web_url = "https://rms-uat.cartodb.com/api/v2/sql?format=CSV&filename=data%20&q=SELECT%20*%20FROM%20%20ds_aadt_reference"
download_fp = os.path.join(traffic_data_dir, 'ds_aadt_reference.csv')
try: 
    urllib.request.urlretrieve(web_url, download_fp)
except:
    print("No file available.")

# Read and view data
ds_aadt_reference_df = pd.read_csv(download_fp)
ds_aadt_reference_df.head()

,the_geom,cartodb_id,the_geom_webmercator,record_id,station_key,station_id,name,road_name,full_name,common_road_name,...,vehicle_classifier,lambert_easting,lambert_northing,wgs84_latitude,wgs84_longitude,direction_seq,quality_rating,publish,md5,updated_on
0,NaN,1791,NaN,NaN,15828002,7211,Lily Lane,Lily Lane,"Lily Lane, South of Fern Circuit",Lily Lane,...,1,9740191,4524353.5,-32.940571,151.713120,7,5,1,be6e76534a9cbe57941a6971d910a6eb,2018-06-12 02:48:41.978017+00
1,NaN,1792,NaN,NaN,58612,97340,Oxley Avenue,Oxley Avenue,"Oxley Avenue, North of High Street",Oxley Avenue,...,0,9163953,4473475.5,-33.480766,145.534805,9,5,1,417b961c9a41b3a2f7ce41fa423d8977,2018-06-12 02:48:41.978017+00
2,NaN,1793,NaN,NaN,56692,19035,Sydenham Road,Sydenham Road,"Sydenham Road, West of Victoria Road",Sydenham Road,...,0,9684475,4419245.0,-33.909630,151.162048,10,5,1,710efc78db32af23f3a6ed4870bc7aeb,2018-06-12 02:48:41.978017+00
3,NaN,1794,NaN,NaN,58856,99931,Castlereagh Highway,Castlereagh Highway,"Castlereagh Highway, South of Abattoirs Road",Castlereagh Highway,...,1,9539223,4573615.5,-32.559254,149.549698,9,5,1,4dbb7f7bd091635de8b3a10399455245,2018-06-12 02:48:41.978017+00
4,NaN,1795,NaN,NaN,56098,05622,Hanbury Street,Hanbury Street,"Hanbury Street, East of Waratah Street",Hanbury Street,...,0,9742526,4528977.0,-32.897934,151.735840,9,5,1,b5b01373fb1bc06495989748e45e918b,2018-06-12 02:48:41.978017+00

In [6]:
# ds_aadt_summary_data
web_url = "https://rms-uat.cartodb.com/api/v2/sql?format=CSV&filename=data%20&q=SELECT%20*%20FROM%20%20ds_aadt_summary_data"
download_fp = os.path.join(traffic_data_dir, 'ds_aadt_summary_data.csv')
try: 
    urllib.request.urlretrieve(web_url, download_fp)
except:
    print("No file available.")

# Read and view data
ds_aadt_summary_data_df = pd.read_csv(download_fp)
ds_aadt_summary_data_df.head()

,the_geom,cartodb_id,the_geom_webmercator,record_id,station_key,station_id,traffic_direction_seq,traffic_direction_name,cardinal_direction_seq,cardinal_direction_name,...,traffic_count,data_start_date,data_end_date,data_duration,data_availability,data_reliability,data_quality_indicator,publish,updated_on,md5
0,NaN,584072,NaN,NaN,57103,53001,0,COUNTER,5,SOUTH,...,16801,NaN,NaN,NaN,-1,-1,0,1,2021-08-04 11:41:27.927875+00,ea52830029714d070f0b077937db2657
1,NaN,584073,NaN,NaN,56950,42001,2,PRESCRIBED AND COUNTER,9,BOTH,...,139,NaN,NaN,NaN,-1,-1,0,1,2021-08-04 11:41:27.927875+00,19c71171ebe793c544eed4008a7fd2a8
2,NaN,264076,NaN,NaN,55318,02015,2,PRESCRIBED AND COUNTER,9,BOTH,...,39273,NaN,NaN,NaN,-1,-1,0,1,2018-12-14 05:33:24.64657+00,2c3a9b9bf222b4b98d5da5b20455e378
3,NaN,584074,NaN,NaN,15334030,T0342,0,COUNTER,3,EAST,...,761,NaN,NaN,NaN,48,91,0,1,2021-08-04 11:41:27.927875+00,1fef957b2dc3ec4592da6be4639f82ec
4,NaN,584075,NaN,NaN,21606001,6118,2,PRESCRIBED AND COUNTER,9,BOTH,...,278,NaN,NaN,NaN,-1,-1,0,1,2021-08-04 11:41:27.927875+00,be37fb416b55b02c7504684893fa1fc8

In [7]:
# ds_aadt_permanent_hourly_data
# Note - results in ~600mb of data (may take a while to download)
web_url = "https://rms-uat.cartodb.com/api/v2/sql?format=CSV&filename=data%20&q=SELECT%20*%20FROM%20%20ds_aadt_permanent_hourly_data"
download_fp = os.path.join(traffic_data_dir, 'ds_aadt_permanent_hourly_data.csv')
try: 
    urllib.request.urlretrieve(web_url, download_fp)
except:
    print("No file available.")

# Read and view data
ds_aadt_permanent_hourly_data_df = pd.read_csv(download_fp)
ds_aadt_permanent_hourly_data_df.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (39) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,the_geom,cartodb_id,the_geom_webmercator,record_id,station_key,traffic_direction_seq,cardinal_direction_seq,classification_seq,date,year,...,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,updated_on,md5
0,NaN,293075,NaN,293075.0,56422,1,7,0,2010-07-07,2010,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,369287d360274f609eb1e9ec729df6e0
1,NaN,1312878,NaN,1312878.0,57105,1,1,3,2009-04-04,2009,...,17.0,20.0,15.0,10.0,7.0,6.0,7.0,3.0,NaN,56fb29cee4980eb3dfdd948514dba889
2,NaN,102066,NaN,102066.0,55786,1,3,0,2011-10-25,2011,...,38.0,6.0,3.0,3.0,1.0,2.0,2.0,2.0,NaN,2c097340acd5dc43e3fc67a8aead7d4b
3,NaN,100176,NaN,100176.0,55747,0,5,0,2009-06-17,2009,...,967.0,1114.0,1149.0,784.0,303.0,190.0,109.0,58.0,NaN,db283035674d8d0987861edea9adb45f
4,NaN,102059,NaN,102059.0,55786,1,3,0,2011-09-07,2011,...,30.0,13.0,0.0,1.0,2.0,0.0,1.0,0.0,NaN,724f407abe3de96210044ea01d2f9026

In [8]:
# ds_aadt_sample_hourly_data
web_url = "https://rms-uat.cartodb.com/api/v2/sql?format=CSV&filename=data%20&q=SELECT%20*%20FROM%20%20ds_aadt_sample_hourly_data"
download_fp = os.path.join(traffic_data_dir, 'ds_aadt_sample_hourly_data.csv')
try: 
    urllib.request.urlretrieve(web_url, download_fp)
except:
    print("No file available.")

# Read and view data
ds_aadt_sample_hourly_data_df = pd.read_csv(download_fp)
ds_aadt_sample_hourly_data_df.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (40) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,the_geom,cartodb_id,the_geom_webmercator,record_id,station_key,traffic_direction_seq,cardinal_direction_seq,classification_seq,date,year,...,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,md5,updated_on
0,NaN,226714,NaN,NaN,58308,0,3,0,2010-05-24,2010,...,23.0,20.0,17.0,3.0,5.0,5.0,1.0,0.0,a0c8608b8d15dfd8b28c96bdff96ea6f,2018-06-12 05:16:50.885412+00
1,NaN,226715,NaN,NaN,58260,1,7,0,2006-05-10,2006,...,17.0,16.0,8.0,3.0,5.0,6.0,4.0,2.0,264a654a854aaf481c21b748d5ac18d3,2018-06-12 05:16:50.885412+00
2,NaN,226716,NaN,NaN,58333,0,3,0,2006-05-11,2006,...,17.0,18.0,8.0,3.0,3.0,3.0,0.0,1.0,9bdadee8611e83b6caba5ac6507ba0a0,2018-06-12 05:16:50.885412+00
3,NaN,226717,NaN,NaN,58308,1,7,0,2010-05-31,2010,...,7.0,11.0,8.0,3.0,2.0,1.0,0.0,2.0,70b9c041abfc5e27a8016c6ff1ce75a3,2018-06-12 05:16:50.885412+00
4,NaN,226718,NaN,NaN,58308,0,3,0,2006-05-14,2006,...,11.0,10.0,12.0,8.0,2.0,2.0,0.0,0.0,99fd24bfc22ded71840ab214723c8b4d,2018-06-12 05:16:50.885412+00